// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  grade: __t.u8(),
  position: __t.u32(),
  playerId: __t.string(),
  playerName: __t.string(),
  rank: __t.string(),
  division: __t.string(),
  masteryPercent: __t.u32(),
  speedPercent: __t.u32(),
});
