// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("PerformanceSnapshot", {
  id: __t.u64(),
  playerId: __t.string(),
  timestamp: __t.timestamp(),
  grade: __t.u8(),
  track: __t.option(__t.string()),
  rank: __t.option(__t.string()),
  division: __t.option(__t.string()),
  factsMasteredAtSnapshot: __t.u32(),
  problemsAttempted: __t.u32(),
  problemsCorrect: __t.u32(),
  sessionSeconds: __t.u32(),
  damageDealt: __t.u32(),
  raidType: __t.option(__t.string()),
  timebackUnitsAtSnapshot: __t.u32(),
  bossLevel: __t.u8(),
  victory: __t.option(__t.bool()),
});


