// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("Player", {
  id: __t.string(),
  name: __t.string(),
  grade: __t.u8(),
  rank: __t.option(__t.string()),
  totalProblems: __t.u32(),
  totalCorrect: __t.u32(),
  avgResponseMs: __t.u32(),
  bestResponseMs: __t.u32(),
  totalRaids: __t.u32(),
  quests: __t.option(__t.string()),
  lastPlayed: __t.timestamp(),
  lastRaid: __t.timestamp(),
  lastWeeklyReset: __t.timestamp(),
  totalAp: __t.u32(),
  inRaidId: __t.option(__t.u64()),
  timebackId: __t.option(__t.string()),
  email: __t.option(__t.string()),
});


