// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  playerId: __t.string(),
  payload: __t.string(),
  createdAt: __t.timestamp(),
  sent: __t.bool(),
  attempts: __t.u8(),
  nextRetryAt: __t.option(__t.timestamp()),
  lastError: __t.option(__t.string()),
  sentAt: __t.option(__t.timestamp()),
});
