// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.10.0 (commit 1d576dc75ca066879f6d9ee4d156c5bce940bd31).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  convertToAccessorMap as __convertToAccessorMap,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import and reexport all reducer arg types
import AdminResetPlayer from "./admin_reset_player_reducer";
export { AdminResetPlayer };
import BulkRestoreFactMastery from "./bulk_restore_fact_mastery_reducer";
export { BulkRestoreFactMastery };
import BulkRestorePerformanceSnapshot from "./bulk_restore_performance_snapshot_reducer";
export { BulkRestorePerformanceSnapshot };
import BulkRestorePlayer from "./bulk_restore_player_reducer";
export { BulkRestorePlayer };
import CheckRaidTimeout from "./check_raid_timeout_reducer";
export { CheckRaidTimeout };
import CleanupAbandonedRaids from "./cleanup_abandoned_raids_reducer";
export { CleanupAbandonedRaids };
import Connect from "./connect_reducer";
export { Connect };
import CountdownComplete from "./countdown_complete_reducer";
export { CountdownComplete };
import CreatePrivateRoom from "./create_private_room_reducer";
export { CreatePrivateRoom };
import CreateSession from "./create_session_reducer";
export { CreateSession };
import JoinPrivateRoom from "./join_private_room_reducer";
export { JoinPrivateRoom };
import LeaveCompletedRaid from "./leave_completed_raid_reducer";
export { LeaveCompletedRaid };
import LeaveRaid from "./leave_raid_reducer";
export { LeaveRaid };
import MarkEventSent from "./mark_event_sent_reducer";
export { MarkEventSent };
import OnDisconnect from "./on_disconnect_reducer";
export { OnDisconnect };
import OpenLootChest from "./open_loot_chest_reducer";
export { OpenLootChest };
import RaidAgain from "./raid_again_reducer";
export { RaidAgain };
import RequestProblem from "./request_problem_reducer";
export { RequestProblem };
import SetBossVisual from "./set_boss_visual_reducer";
export { SetBossVisual };
import SetGrade from "./set_grade_reducer";
export { SetGrade };
import SetMasteryBoss from "./set_mastery_boss_reducer";
export { SetMasteryBoss };
import SetTimebackId from "./set_timeback_id_reducer";
export { SetTimebackId };
import SoloAgain from "./solo_again_reducer";
export { SoloAgain };
import StartRaidManual from "./start_raid_manual_reducer";
export { StartRaidManual };
import StartRematch from "./start_rematch_reducer";
export { StartRematch };
import StartSoloRaid from "./start_solo_raid_reducer";
export { StartSoloRaid };
import SubmitAnswer from "./submit_answer_reducer";
export { SubmitAnswer };
import TestCreateTimebackEvent from "./test_create_timeback_event_reducer";
export { TestCreateTimebackEvent };
import ToggleReady from "./toggle_ready_reducer";
export { ToggleReady };

// Import and reexport all procedure arg types

// Import and reexport all table handle types
import AuthorizedWorkerRow from "./authorized_worker_table";
export { AuthorizedWorkerRow };
import CleanupScheduleRow from "./cleanup_schedule_table";
export { CleanupScheduleRow };
import CountdownScheduleRow from "./countdown_schedule_table";
export { CountdownScheduleRow };
import FactMasteryRow from "./fact_mastery_table";
export { FactMasteryRow };
import LeaderboardEntryRow from "./leaderboard_entry_table";
export { LeaderboardEntryRow };
import MyPlayerRow from "./my_player_table";
export { MyPlayerRow };
import PerformanceSnapshotRow from "./performance_snapshot_table";
export { PerformanceSnapshotRow };
import PlayerRow from "./player_table";
export { PlayerRow };
import PlayerAnswerRow from "./player_answer_table";
export { PlayerAnswerRow };
import ProblemRow from "./problem_table";
export { ProblemRow };
import RaidRow from "./raid_table";
export { RaidRow };
import RaidPlayerRow from "./raid_player_table";
export { RaidPlayerRow };
import RaidTimeoutScheduleRow from "./raid_timeout_schedule_table";
export { RaidTimeoutScheduleRow };
import SessionRow from "./session_table";
export { SessionRow };
import TimebackEventQueueRow from "./timeback_event_queue_table";
export { TimebackEventQueueRow };

// Import and reexport all types
import AttemptRecord from "./attempt_record_type";
export { AttemptRecord };
import AuthorizedWorker from "./authorized_worker_type";
export { AuthorizedWorker };
import CleanupSchedule from "./cleanup_schedule_type";
export { CleanupSchedule };
import CountdownSchedule from "./countdown_schedule_type";
export { CountdownSchedule };
import FactMastery from "./fact_mastery_type";
export { FactMastery };
import LeaderboardEntry from "./leaderboard_entry_type";
export { LeaderboardEntry };
import Operation from "./operation_type";
export { Operation };
import PerformanceSnapshot from "./performance_snapshot_type";
export { PerformanceSnapshot };
import Player from "./player_type";
export { Player };
import PlayerAnswer from "./player_answer_type";
export { PlayerAnswer };
import Problem from "./problem_type";
export { Problem };
import Raid from "./raid_type";
export { Raid };
import RaidPlayer from "./raid_player_type";
export { RaidPlayer };
import RaidState from "./raid_state_type";
export { RaidState };
import RaidTimeoutSchedule from "./raid_timeout_schedule_type";
export { RaidTimeoutSchedule };
import Session from "./session_type";
export { Session };
import TimebackEventQueue from "./timeback_event_queue_type";
export { TimebackEventQueue };

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema(
  __table({
    name: 'authorized_worker',
    indexes: [
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'authorized_worker_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, AuthorizedWorkerRow),
  __table({
    name: 'cleanup_schedule',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'cleanup_schedule_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CleanupScheduleRow),
  __table({
    name: 'countdown_schedule',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'countdown_schedule_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CountdownScheduleRow),
  __table({
    name: 'fact_mastery',
    indexes: [
      { name: 'fact_key', algorithm: 'btree', columns: [
        'factKey',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'player_id', algorithm: 'btree', columns: [
        'playerId',
      ] },
    ],
    constraints: [
      { name: 'fact_mastery_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, FactMasteryRow),
  __table({
    name: 'leaderboard_entry',
    indexes: [
      { name: 'grade', algorithm: 'btree', columns: [
        'grade',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'leaderboard_entry_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, LeaderboardEntryRow),
  __table({
    name: 'performance_snapshot',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'player_id', algorithm: 'btree', columns: [
        'playerId',
      ] },
    ],
    constraints: [
      { name: 'performance_snapshot_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PerformanceSnapshotRow),
  __table({
    name: 'player',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'player_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PlayerRow),
  __table({
    name: 'player_answer',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'player_id', algorithm: 'btree', columns: [
        'playerId',
      ] },
      { name: 'problem_id', algorithm: 'btree', columns: [
        'problemId',
      ] },
    ],
    constraints: [
      { name: 'player_answer_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PlayerAnswerRow),
  __table({
    name: 'problem',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'player_id', algorithm: 'btree', columns: [
        'playerId',
      ] },
      { name: 'raid_id', algorithm: 'btree', columns: [
        'raidId',
      ] },
      { name: 'idx_raid_player', algorithm: 'btree', columns: [
        'raidId',
        'playerId',
      ] },
    ],
    constraints: [
      { name: 'problem_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ProblemRow),
  __table({
    name: 'raid',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'raid_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, RaidRow),
  __table({
    name: 'raid_player',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'player_id', algorithm: 'btree', columns: [
        'playerId',
      ] },
      { name: 'raid_id', algorithm: 'btree', columns: [
        'raidId',
      ] },
    ],
    constraints: [
      { name: 'raid_player_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, RaidPlayerRow),
  __table({
    name: 'raid_timeout_schedule',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'raid_timeout_schedule_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, RaidTimeoutScheduleRow),
  __table({
    name: 'session',
    indexes: [
      { name: 'connection_id', algorithm: 'btree', columns: [
        'connectionId',
      ] },
    ],
    constraints: [
      { name: 'session_connection_id_key', constraint: 'unique', columns: ['connectionId'] },
    ],
  }, SessionRow),
  __table({
    name: 'timeback_event_queue',
    indexes: [
      { name: 'created_at', algorithm: 'btree', columns: [
        'createdAt',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'next_retry_at', algorithm: 'btree', columns: [
        'nextRetryAt',
      ] },
      { name: 'player_id', algorithm: 'btree', columns: [
        'playerId',
      ] },
      { name: 'sent', algorithm: 'btree', columns: [
        'sent',
      ] },
    ],
    constraints: [
      { name: 'timeback_event_queue_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TimebackEventQueueRow),
  __table({
    name: 'my_player',
    indexes: [
    ],
    constraints: [
    ],
  }, MyPlayerRow),
);

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("admin_reset_player", AdminResetPlayer),
  __reducerSchema("bulk_restore_fact_mastery", BulkRestoreFactMastery),
  __reducerSchema("bulk_restore_performance_snapshot", BulkRestorePerformanceSnapshot),
  __reducerSchema("bulk_restore_player", BulkRestorePlayer),
  __reducerSchema("check_raid_timeout", CheckRaidTimeout),
  __reducerSchema("cleanup_abandoned_raids", CleanupAbandonedRaids),
  __reducerSchema("connect", Connect),
  __reducerSchema("countdown_complete", CountdownComplete),
  __reducerSchema("create_private_room", CreatePrivateRoom),
  __reducerSchema("create_session", CreateSession),
  __reducerSchema("join_private_room", JoinPrivateRoom),
  __reducerSchema("leave_completed_raid", LeaveCompletedRaid),
  __reducerSchema("leave_raid", LeaveRaid),
  __reducerSchema("mark_event_sent", MarkEventSent),
  __reducerSchema("open_loot_chest", OpenLootChest),
  __reducerSchema("raid_again", RaidAgain),
  __reducerSchema("request_problem", RequestProblem),
  __reducerSchema("set_boss_visual", SetBossVisual),
  __reducerSchema("set_grade", SetGrade),
  __reducerSchema("set_mastery_boss", SetMasteryBoss),
  __reducerSchema("set_timeback_id", SetTimebackId),
  __reducerSchema("solo_again", SoloAgain),
  __reducerSchema("start_raid_manual", StartRaidManual),
  __reducerSchema("start_rematch", StartRematch),
  __reducerSchema("start_solo_raid", StartSoloRaid),
  __reducerSchema("submit_answer", SubmitAnswer),
  __reducerSchema("test_create_timeback_event", TestCreateTimebackEvent),
  __reducerSchema("toggle_ready", ToggleReady),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "1.10.0" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. */
export const tables = __convertToAccessorMap(tablesSchema.schemaType.tables);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

