// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("PlayerAnswer", {
  id: __t.u64(),
  problemId: __t.u64(),
  playerId: __t.string(),
  responseMs: __t.u32(),
  isCorrect: __t.bool(),
  damage: __t.u32(),
});


