// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  playerId: __t.string(),
  raidId: __t.u64(),
  playerName: __t.string(),
  grade: __t.u8(),
  rank: __t.option(__t.string()),
  division: __t.option(__t.string()),
  isActive: __t.bool(),
  damageDealt: __t.u32(),
  problemsAnswered: __t.u32(),
  correctAnswers: __t.u32(),
  fastestAnswerMs: __t.u32(),
  isReady: __t.bool(),
  isLeader: __t.bool(),
  recentProblems: __t.string(),
  pendingChestBonus: __t.option(__t.u32()),
  track: __t.option(__t.string()),
});
