// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type TableHandle as __TableHandle,
} from "spacetimedb";
import { AttemptRecord } from "./attempt_record_type";
// Mark import as potentially unused
declare type __keep_AttemptRecord = AttemptRecord;


export type FactMastery = {
  id: bigint,
  playerId: string,
  factKey: string,
  totalAttempts: number,
  totalCorrect: number,
  lastSeen: __Timestamp,
  avgResponseMs: number,
  fastestMs: number,
  recentAttempts: AttemptRecord[],
  masteryLevel: number,
};
let _cached_FactMastery_type_value: __AlgebraicTypeType | null = null;

/**
 * An object for generated helper functions.
 */
export const FactMastery = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    if (_cached_FactMastery_type_value) return _cached_FactMastery_type_value;
    _cached_FactMastery_type_value = __AlgebraicTypeValue.Product({ elements: [] });
    _cached_FactMastery_type_value.value.elements.push(
      { name: "id", algebraicType: __AlgebraicTypeValue.U64 },
      { name: "playerId", algebraicType: __AlgebraicTypeValue.String },
      { name: "factKey", algebraicType: __AlgebraicTypeValue.String },
      { name: "totalAttempts", algebraicType: __AlgebraicTypeValue.U32 },
      { name: "totalCorrect", algebraicType: __AlgebraicTypeValue.U32 },
      { name: "lastSeen", algebraicType: __AlgebraicTypeValue.createTimestampType() },
      { name: "avgResponseMs", algebraicType: __AlgebraicTypeValue.U32 },
      { name: "fastestMs", algebraicType: __AlgebraicTypeValue.U32 },
      { name: "recentAttempts", algebraicType: __AlgebraicTypeValue.Array(AttemptRecord.getTypeScriptAlgebraicType()) },
      { name: "masteryLevel", algebraicType: __AlgebraicTypeValue.U8 },
    );
    return _cached_FactMastery_type_value;
  },

  serialize(writer: __BinaryWriter, value: FactMastery): void {
    __AlgebraicTypeValue.serializeValue(writer, FactMastery.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): FactMastery {
    return __AlgebraicTypeValue.deserializeValue(reader, FactMastery.getTypeScriptAlgebraicType());
  },

}

export default FactMastery;


