// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.6.0 (commit 3c16edb3503eab8aad562e011d7fb452e051267d).

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type TableHandle as __TableHandle,
} from "spacetimedb";

// Import and reexport all reducer arg types
import { BulkRestoreFactMastery } from "./bulk_restore_fact_mastery_reducer.ts";
export { BulkRestoreFactMastery };
import { BulkRestorePerformanceSnapshot } from "./bulk_restore_performance_snapshot_reducer.ts";
export { BulkRestorePerformanceSnapshot };
import { BulkRestorePlayer } from "./bulk_restore_player_reducer.ts";
export { BulkRestorePlayer };
import { CheckRaidTimeout } from "./check_raid_timeout_reducer.ts";
export { CheckRaidTimeout };
import { CleanupAbandonedRaids } from "./cleanup_abandoned_raids_reducer.ts";
export { CleanupAbandonedRaids };
import { Connect } from "./connect_reducer.ts";
export { Connect };
import { CreatePrivateRoom } from "./create_private_room_reducer.ts";
export { CreatePrivateRoom };
import { JoinPrivateRoom } from "./join_private_room_reducer.ts";
export { JoinPrivateRoom };
import { LeaveCompletedRaid } from "./leave_completed_raid_reducer.ts";
export { LeaveCompletedRaid };
import { LeaveRaid } from "./leave_raid_reducer.ts";
export { LeaveRaid };
import { MarkEventSent } from "./mark_event_sent_reducer.ts";
export { MarkEventSent };
import { OnDisconnect } from "./on_disconnect_reducer.ts";
export { OnDisconnect };
import { OpenLootChest } from "./open_loot_chest_reducer.ts";
export { OpenLootChest };
import { RaidAgain } from "./raid_again_reducer.ts";
export { RaidAgain };
import { RequestProblem } from "./request_problem_reducer.ts";
export { RequestProblem };
import { SetGrade } from "./set_grade_reducer.ts";
export { SetGrade };
import { SoloAgain } from "./solo_again_reducer.ts";
export { SoloAgain };
import { StartRaidManual } from "./start_raid_manual_reducer.ts";
export { StartRaidManual };
import { StartRematch } from "./start_rematch_reducer.ts";
export { StartRematch };
import { StartSoloRaid } from "./start_solo_raid_reducer.ts";
export { StartSoloRaid };
import { SubmitAnswer } from "./submit_answer_reducer.ts";
export { SubmitAnswer };
import { TestCreateTimebackEvent } from "./test_create_timeback_event_reducer.ts";
export { TestCreateTimebackEvent };
import { ToggleReady } from "./toggle_ready_reducer.ts";
export { ToggleReady };

// Import and reexport all table handle types
import { AuthorizedWorkerTableHandle } from "./authorized_worker_table.ts";
export { AuthorizedWorkerTableHandle };
import { CleanupScheduleTableHandle } from "./cleanup_schedule_table.ts";
export { CleanupScheduleTableHandle };
import { FactMasteryTableHandle } from "./fact_mastery_table.ts";
export { FactMasteryTableHandle };
import { LeaderboardEntryTableHandle } from "./leaderboard_entry_table.ts";
export { LeaderboardEntryTableHandle };
import { PerformanceSnapshotTableHandle } from "./performance_snapshot_table.ts";
export { PerformanceSnapshotTableHandle };
import { PlayerTableHandle } from "./player_table.ts";
export { PlayerTableHandle };
import { PlayerAnswerTableHandle } from "./player_answer_table.ts";
export { PlayerAnswerTableHandle };
import { ProblemTableHandle } from "./problem_table.ts";
export { ProblemTableHandle };
import { RaidTableHandle } from "./raid_table.ts";
export { RaidTableHandle };
import { RaidPlayerTableHandle } from "./raid_player_table.ts";
export { RaidPlayerTableHandle };
import { RaidTimeoutScheduleTableHandle } from "./raid_timeout_schedule_table.ts";
export { RaidTimeoutScheduleTableHandle };
import { SessionTableHandle } from "./session_table.ts";
export { SessionTableHandle };
import { TimebackEventQueueTableHandle } from "./timeback_event_queue_table.ts";
export { TimebackEventQueueTableHandle };

// Import and reexport all types
import { AttemptRecord } from "./attempt_record_type.ts";
export { AttemptRecord };
import { AuthorizedWorker } from "./authorized_worker_type.ts";
export { AuthorizedWorker };
import { CleanupSchedule } from "./cleanup_schedule_type.ts";
export { CleanupSchedule };
import { FactMastery } from "./fact_mastery_type.ts";
export { FactMastery };
import { LeaderboardEntry } from "./leaderboard_entry_type.ts";
export { LeaderboardEntry };
import { Operation } from "./operation_type.ts";
export { Operation };
import { PerformanceSnapshot } from "./performance_snapshot_type.ts";
export { PerformanceSnapshot };
import { Player } from "./player_type.ts";
export { Player };
import { PlayerAnswer } from "./player_answer_type.ts";
export { PlayerAnswer };
import { Problem } from "./problem_type.ts";
export { Problem };
import { Raid } from "./raid_type.ts";
export { Raid };
import { RaidPlayer } from "./raid_player_type.ts";
export { RaidPlayer };
import { RaidState } from "./raid_state_type.ts";
export { RaidState };
import { RaidTimeoutSchedule } from "./raid_timeout_schedule_type.ts";
export { RaidTimeoutSchedule };
import { Session } from "./session_type.ts";
export { Session };
import { TimebackEventQueue } from "./timeback_event_queue_type.ts";
export { TimebackEventQueue };

const REMOTE_MODULE = {
  tables: {
    authorized_worker: {
      tableName: "authorized_worker" as const,
      rowType: AuthorizedWorker.getTypeScriptAlgebraicType(),
      primaryKey: "identity",
      primaryKeyInfo: {
        colName: "identity",
        colType: (AuthorizedWorker.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    cleanup_schedule: {
      tableName: "cleanup_schedule" as const,
      rowType: CleanupSchedule.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: (CleanupSchedule.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    fact_mastery: {
      tableName: "fact_mastery" as const,
      rowType: FactMastery.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: (FactMastery.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    leaderboard_entry: {
      tableName: "leaderboard_entry" as const,
      rowType: LeaderboardEntry.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: (LeaderboardEntry.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    performance_snapshot: {
      tableName: "performance_snapshot" as const,
      rowType: PerformanceSnapshot.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: (PerformanceSnapshot.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    player: {
      tableName: "player" as const,
      rowType: Player.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: (Player.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    player_answer: {
      tableName: "player_answer" as const,
      rowType: PlayerAnswer.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: (PlayerAnswer.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    problem: {
      tableName: "problem" as const,
      rowType: Problem.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: (Problem.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    raid: {
      tableName: "raid" as const,
      rowType: Raid.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: (Raid.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    raid_player: {
      tableName: "raid_player" as const,
      rowType: RaidPlayer.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: (RaidPlayer.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    raid_timeout_schedule: {
      tableName: "raid_timeout_schedule" as const,
      rowType: RaidTimeoutSchedule.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: (RaidTimeoutSchedule.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    session: {
      tableName: "session" as const,
      rowType: Session.getTypeScriptAlgebraicType(),
      primaryKey: "connectionId",
      primaryKeyInfo: {
        colName: "connectionId",
        colType: (Session.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    timeback_event_queue: {
      tableName: "timeback_event_queue" as const,
      rowType: TimebackEventQueue.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: (TimebackEventQueue.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
  },
  reducers: {
    bulk_restore_fact_mastery: {
      reducerName: "bulk_restore_fact_mastery",
      argsType: BulkRestoreFactMastery.getTypeScriptAlgebraicType(),
    },
    bulk_restore_performance_snapshot: {
      reducerName: "bulk_restore_performance_snapshot",
      argsType: BulkRestorePerformanceSnapshot.getTypeScriptAlgebraicType(),
    },
    bulk_restore_player: {
      reducerName: "bulk_restore_player",
      argsType: BulkRestorePlayer.getTypeScriptAlgebraicType(),
    },
    check_raid_timeout: {
      reducerName: "check_raid_timeout",
      argsType: CheckRaidTimeout.getTypeScriptAlgebraicType(),
    },
    cleanup_abandoned_raids: {
      reducerName: "cleanup_abandoned_raids",
      argsType: CleanupAbandonedRaids.getTypeScriptAlgebraicType(),
    },
    connect: {
      reducerName: "connect",
      argsType: Connect.getTypeScriptAlgebraicType(),
    },
    create_private_room: {
      reducerName: "create_private_room",
      argsType: CreatePrivateRoom.getTypeScriptAlgebraicType(),
    },
    join_private_room: {
      reducerName: "join_private_room",
      argsType: JoinPrivateRoom.getTypeScriptAlgebraicType(),
    },
    leave_completed_raid: {
      reducerName: "leave_completed_raid",
      argsType: LeaveCompletedRaid.getTypeScriptAlgebraicType(),
    },
    leave_raid: {
      reducerName: "leave_raid",
      argsType: LeaveRaid.getTypeScriptAlgebraicType(),
    },
    mark_event_sent: {
      reducerName: "mark_event_sent",
      argsType: MarkEventSent.getTypeScriptAlgebraicType(),
    },
    on_disconnect: {
      reducerName: "on_disconnect",
      argsType: OnDisconnect.getTypeScriptAlgebraicType(),
    },
    open_loot_chest: {
      reducerName: "open_loot_chest",
      argsType: OpenLootChest.getTypeScriptAlgebraicType(),
    },
    raid_again: {
      reducerName: "raid_again",
      argsType: RaidAgain.getTypeScriptAlgebraicType(),
    },
    request_problem: {
      reducerName: "request_problem",
      argsType: RequestProblem.getTypeScriptAlgebraicType(),
    },
    set_grade: {
      reducerName: "set_grade",
      argsType: SetGrade.getTypeScriptAlgebraicType(),
    },
    solo_again: {
      reducerName: "solo_again",
      argsType: SoloAgain.getTypeScriptAlgebraicType(),
    },
    start_raid_manual: {
      reducerName: "start_raid_manual",
      argsType: StartRaidManual.getTypeScriptAlgebraicType(),
    },
    start_rematch: {
      reducerName: "start_rematch",
      argsType: StartRematch.getTypeScriptAlgebraicType(),
    },
    start_solo_raid: {
      reducerName: "start_solo_raid",
      argsType: StartSoloRaid.getTypeScriptAlgebraicType(),
    },
    submit_answer: {
      reducerName: "submit_answer",
      argsType: SubmitAnswer.getTypeScriptAlgebraicType(),
    },
    test_create_timeback_event: {
      reducerName: "test_create_timeback_event",
      argsType: TestCreateTimebackEvent.getTypeScriptAlgebraicType(),
    },
    toggle_ready: {
      reducerName: "toggle_ready",
      argsType: ToggleReady.getTypeScriptAlgebraicType(),
    },
  },
  versionInfo: {
    cliVersion: "1.6.0",
  },
  // Constructors which are used by the DbConnectionImpl to
  // extract type information from the generated RemoteModule.
  //
  // NOTE: This is not strictly necessary for `eventContextConstructor` because
  // all we do is build a TypeScript object which we could have done inside the
  // SDK, but if in the future we wanted to create a class this would be
  // necessary because classes have methods, so we'll keep it.
  eventContextConstructor: (imp: __DbConnectionImpl, event: __Event<Reducer>) => {
    return {
      ...(imp as DbConnection),
      event
    }
  },
  dbViewConstructor: (imp: __DbConnectionImpl) => {
    return new RemoteTables(imp);
  },
  reducersConstructor: (imp: __DbConnectionImpl, setReducerFlags: SetReducerFlags) => {
    return new RemoteReducers(imp, setReducerFlags);
  },
  setReducerFlagsConstructor: () => {
    return new SetReducerFlags();
  }
}

// A type representing all the possible variants of a reducer.
export type Reducer = never
| { name: "BulkRestoreFactMastery", args: BulkRestoreFactMastery }
| { name: "BulkRestorePerformanceSnapshot", args: BulkRestorePerformanceSnapshot }
| { name: "BulkRestorePlayer", args: BulkRestorePlayer }
| { name: "CheckRaidTimeout", args: CheckRaidTimeout }
| { name: "CleanupAbandonedRaids", args: CleanupAbandonedRaids }
| { name: "Connect", args: Connect }
| { name: "CreatePrivateRoom", args: CreatePrivateRoom }
| { name: "JoinPrivateRoom", args: JoinPrivateRoom }
| { name: "LeaveCompletedRaid", args: LeaveCompletedRaid }
| { name: "LeaveRaid", args: LeaveRaid }
| { name: "MarkEventSent", args: MarkEventSent }
| { name: "OnDisconnect", args: OnDisconnect }
| { name: "OpenLootChest", args: OpenLootChest }
| { name: "RaidAgain", args: RaidAgain }
| { name: "RequestProblem", args: RequestProblem }
| { name: "SetGrade", args: SetGrade }
| { name: "SoloAgain", args: SoloAgain }
| { name: "StartRaidManual", args: StartRaidManual }
| { name: "StartRematch", args: StartRematch }
| { name: "StartSoloRaid", args: StartSoloRaid }
| { name: "SubmitAnswer", args: SubmitAnswer }
| { name: "TestCreateTimebackEvent", args: TestCreateTimebackEvent }
| { name: "ToggleReady", args: ToggleReady }
;

export class RemoteReducers {
  constructor(private connection: __DbConnectionImpl, private setCallReducerFlags: SetReducerFlags) {}

  bulkRestoreFactMastery(jsonData: string) {
    const __args = { jsonData };
    let __writer = new __BinaryWriter(1024);
    BulkRestoreFactMastery.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("bulk_restore_fact_mastery", __argsBuffer, this.setCallReducerFlags.bulkRestoreFactMasteryFlags);
  }

  onBulkRestoreFactMastery(callback: (ctx: ReducerEventContext, jsonData: string) => void) {
    this.connection.onReducer("bulk_restore_fact_mastery", callback);
  }

  removeOnBulkRestoreFactMastery(callback: (ctx: ReducerEventContext, jsonData: string) => void) {
    this.connection.offReducer("bulk_restore_fact_mastery", callback);
  }

  bulkRestorePerformanceSnapshot(jsonData: string) {
    const __args = { jsonData };
    let __writer = new __BinaryWriter(1024);
    BulkRestorePerformanceSnapshot.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("bulk_restore_performance_snapshot", __argsBuffer, this.setCallReducerFlags.bulkRestorePerformanceSnapshotFlags);
  }

  onBulkRestorePerformanceSnapshot(callback: (ctx: ReducerEventContext, jsonData: string) => void) {
    this.connection.onReducer("bulk_restore_performance_snapshot", callback);
  }

  removeOnBulkRestorePerformanceSnapshot(callback: (ctx: ReducerEventContext, jsonData: string) => void) {
    this.connection.offReducer("bulk_restore_performance_snapshot", callback);
  }

  bulkRestorePlayer(jsonData: string) {
    const __args = { jsonData };
    let __writer = new __BinaryWriter(1024);
    BulkRestorePlayer.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("bulk_restore_player", __argsBuffer, this.setCallReducerFlags.bulkRestorePlayerFlags);
  }

  onBulkRestorePlayer(callback: (ctx: ReducerEventContext, jsonData: string) => void) {
    this.connection.onReducer("bulk_restore_player", callback);
  }

  removeOnBulkRestorePlayer(callback: (ctx: ReducerEventContext, jsonData: string) => void) {
    this.connection.offReducer("bulk_restore_player", callback);
  }

  checkRaidTimeout(schedule: RaidTimeoutSchedule) {
    const __args = { schedule };
    let __writer = new __BinaryWriter(1024);
    CheckRaidTimeout.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("check_raid_timeout", __argsBuffer, this.setCallReducerFlags.checkRaidTimeoutFlags);
  }

  onCheckRaidTimeout(callback: (ctx: ReducerEventContext, schedule: RaidTimeoutSchedule) => void) {
    this.connection.onReducer("check_raid_timeout", callback);
  }

  removeOnCheckRaidTimeout(callback: (ctx: ReducerEventContext, schedule: RaidTimeoutSchedule) => void) {
    this.connection.offReducer("check_raid_timeout", callback);
  }

  cleanupAbandonedRaids(schedule: CleanupSchedule) {
    const __args = { schedule };
    let __writer = new __BinaryWriter(1024);
    CleanupAbandonedRaids.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("cleanup_abandoned_raids", __argsBuffer, this.setCallReducerFlags.cleanupAbandonedRaidsFlags);
  }

  onCleanupAbandonedRaids(callback: (ctx: ReducerEventContext, schedule: CleanupSchedule) => void) {
    this.connection.onReducer("cleanup_abandoned_raids", callback);
  }

  removeOnCleanupAbandonedRaids(callback: (ctx: ReducerEventContext, schedule: CleanupSchedule) => void) {
    this.connection.offReducer("cleanup_abandoned_raids", callback);
  }

  connect(name: string, playerId: string, grade: number | undefined, timebackId: string | undefined, email: string | undefined) {
    const __args = { name, playerId, grade, timebackId, email };
    let __writer = new __BinaryWriter(1024);
    Connect.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("connect", __argsBuffer, this.setCallReducerFlags.connectFlags);
  }

  onConnect(callback: (ctx: ReducerEventContext, name: string, playerId: string, grade: number | undefined, timebackId: string | undefined, email: string | undefined) => void) {
    this.connection.onReducer("connect", callback);
  }

  removeOnConnect(callback: (ctx: ReducerEventContext, name: string, playerId: string, grade: number | undefined, timebackId: string | undefined, email: string | undefined) => void) {
    this.connection.offReducer("connect", callback);
  }

  createPrivateRoom(track: string | undefined) {
    const __args = { track };
    let __writer = new __BinaryWriter(1024);
    CreatePrivateRoom.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("create_private_room", __argsBuffer, this.setCallReducerFlags.createPrivateRoomFlags);
  }

  onCreatePrivateRoom(callback: (ctx: ReducerEventContext, track: string | undefined) => void) {
    this.connection.onReducer("create_private_room", callback);
  }

  removeOnCreatePrivateRoom(callback: (ctx: ReducerEventContext, track: string | undefined) => void) {
    this.connection.offReducer("create_private_room", callback);
  }

  joinPrivateRoom(code: string, track: string | undefined) {
    const __args = { code, track };
    let __writer = new __BinaryWriter(1024);
    JoinPrivateRoom.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("join_private_room", __argsBuffer, this.setCallReducerFlags.joinPrivateRoomFlags);
  }

  onJoinPrivateRoom(callback: (ctx: ReducerEventContext, code: string, track: string | undefined) => void) {
    this.connection.onReducer("join_private_room", callback);
  }

  removeOnJoinPrivateRoom(callback: (ctx: ReducerEventContext, code: string, track: string | undefined) => void) {
    this.connection.offReducer("join_private_room", callback);
  }

  leaveCompletedRaid() {
    this.connection.callReducer("leave_completed_raid", new Uint8Array(0), this.setCallReducerFlags.leaveCompletedRaidFlags);
  }

  onLeaveCompletedRaid(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("leave_completed_raid", callback);
  }

  removeOnLeaveCompletedRaid(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("leave_completed_raid", callback);
  }

  leaveRaid() {
    this.connection.callReducer("leave_raid", new Uint8Array(0), this.setCallReducerFlags.leaveRaidFlags);
  }

  onLeaveRaid(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("leave_raid", callback);
  }

  removeOnLeaveRaid(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("leave_raid", callback);
  }

  markEventSent(eventId: bigint, error: string | undefined) {
    const __args = { eventId, error };
    let __writer = new __BinaryWriter(1024);
    MarkEventSent.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("mark_event_sent", __argsBuffer, this.setCallReducerFlags.markEventSentFlags);
  }

  onMarkEventSent(callback: (ctx: ReducerEventContext, eventId: bigint, error: string | undefined) => void) {
    this.connection.onReducer("mark_event_sent", callback);
  }

  removeOnMarkEventSent(callback: (ctx: ReducerEventContext, eventId: bigint, error: string | undefined) => void) {
    this.connection.offReducer("mark_event_sent", callback);
  }

  onOnDisconnect(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("on_disconnect", callback);
  }

  removeOnOnDisconnect(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("on_disconnect", callback);
  }

  openLootChest() {
    this.connection.callReducer("open_loot_chest", new Uint8Array(0), this.setCallReducerFlags.openLootChestFlags);
  }

  onOpenLootChest(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("open_loot_chest", callback);
  }

  removeOnOpenLootChest(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("open_loot_chest", callback);
  }

  raidAgain() {
    this.connection.callReducer("raid_again", new Uint8Array(0), this.setCallReducerFlags.raidAgainFlags);
  }

  onRaidAgain(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("raid_again", callback);
  }

  removeOnRaidAgain(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("raid_again", callback);
  }

  requestProblem() {
    this.connection.callReducer("request_problem", new Uint8Array(0), this.setCallReducerFlags.requestProblemFlags);
  }

  onRequestProblem(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("request_problem", callback);
  }

  removeOnRequestProblem(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("request_problem", callback);
  }

  setGrade(grade: number, playerId: string | undefined) {
    const __args = { grade, playerId };
    let __writer = new __BinaryWriter(1024);
    SetGrade.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("set_grade", __argsBuffer, this.setCallReducerFlags.setGradeFlags);
  }

  onSetGrade(callback: (ctx: ReducerEventContext, grade: number, playerId: string | undefined) => void) {
    this.connection.onReducer("set_grade", callback);
  }

  removeOnSetGrade(callback: (ctx: ReducerEventContext, grade: number, playerId: string | undefined) => void) {
    this.connection.offReducer("set_grade", callback);
  }

  soloAgain() {
    this.connection.callReducer("solo_again", new Uint8Array(0), this.setCallReducerFlags.soloAgainFlags);
  }

  onSoloAgain(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("solo_again", callback);
  }

  removeOnSoloAgain(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("solo_again", callback);
  }

  startRaidManual() {
    this.connection.callReducer("start_raid_manual", new Uint8Array(0), this.setCallReducerFlags.startRaidManualFlags);
  }

  onStartRaidManual(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("start_raid_manual", callback);
  }

  removeOnStartRaidManual(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("start_raid_manual", callback);
  }

  startRematch() {
    this.connection.callReducer("start_rematch", new Uint8Array(0), this.setCallReducerFlags.startRematchFlags);
  }

  onStartRematch(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("start_rematch", callback);
  }

  removeOnStartRematch(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("start_rematch", callback);
  }

  startSoloRaid(track: string | undefined) {
    const __args = { track };
    let __writer = new __BinaryWriter(1024);
    StartSoloRaid.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("start_solo_raid", __argsBuffer, this.setCallReducerFlags.startSoloRaidFlags);
  }

  onStartSoloRaid(callback: (ctx: ReducerEventContext, track: string | undefined) => void) {
    this.connection.onReducer("start_solo_raid", callback);
  }

  removeOnStartSoloRaid(callback: (ctx: ReducerEventContext, track: string | undefined) => void) {
    this.connection.offReducer("start_solo_raid", callback);
  }

  submitAnswer(problemId: bigint, answerValue: number, responseMs: number) {
    const __args = { problemId, answerValue, responseMs };
    let __writer = new __BinaryWriter(1024);
    SubmitAnswer.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("submit_answer", __argsBuffer, this.setCallReducerFlags.submitAnswerFlags);
  }

  onSubmitAnswer(callback: (ctx: ReducerEventContext, problemId: bigint, answerValue: number, responseMs: number) => void) {
    this.connection.onReducer("submit_answer", callback);
  }

  removeOnSubmitAnswer(callback: (ctx: ReducerEventContext, problemId: bigint, answerValue: number, responseMs: number) => void) {
    this.connection.offReducer("submit_answer", callback);
  }

  testCreateTimebackEvent(playerId: string, timebackId: string, raidId: bigint, email: string, xpEarned: number, level: number, problemsAnswered: number, correctAnswers: number) {
    const __args = { playerId, timebackId, raidId, email, xpEarned, level, problemsAnswered, correctAnswers };
    let __writer = new __BinaryWriter(1024);
    TestCreateTimebackEvent.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("test_create_timeback_event", __argsBuffer, this.setCallReducerFlags.testCreateTimebackEventFlags);
  }

  onTestCreateTimebackEvent(callback: (ctx: ReducerEventContext, playerId: string, timebackId: string, raidId: bigint, email: string, xpEarned: number, level: number, problemsAnswered: number, correctAnswers: number) => void) {
    this.connection.onReducer("test_create_timeback_event", callback);
  }

  removeOnTestCreateTimebackEvent(callback: (ctx: ReducerEventContext, playerId: string, timebackId: string, raidId: bigint, email: string, xpEarned: number, level: number, problemsAnswered: number, correctAnswers: number) => void) {
    this.connection.offReducer("test_create_timeback_event", callback);
  }

  toggleReady() {
    this.connection.callReducer("toggle_ready", new Uint8Array(0), this.setCallReducerFlags.toggleReadyFlags);
  }

  onToggleReady(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("toggle_ready", callback);
  }

  removeOnToggleReady(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("toggle_ready", callback);
  }

}

export class SetReducerFlags {
  bulkRestoreFactMasteryFlags: __CallReducerFlags = 'FullUpdate';
  bulkRestoreFactMastery(flags: __CallReducerFlags) {
    this.bulkRestoreFactMasteryFlags = flags;
  }

  bulkRestorePerformanceSnapshotFlags: __CallReducerFlags = 'FullUpdate';
  bulkRestorePerformanceSnapshot(flags: __CallReducerFlags) {
    this.bulkRestorePerformanceSnapshotFlags = flags;
  }

  bulkRestorePlayerFlags: __CallReducerFlags = 'FullUpdate';
  bulkRestorePlayer(flags: __CallReducerFlags) {
    this.bulkRestorePlayerFlags = flags;
  }

  checkRaidTimeoutFlags: __CallReducerFlags = 'FullUpdate';
  checkRaidTimeout(flags: __CallReducerFlags) {
    this.checkRaidTimeoutFlags = flags;
  }

  cleanupAbandonedRaidsFlags: __CallReducerFlags = 'FullUpdate';
  cleanupAbandonedRaids(flags: __CallReducerFlags) {
    this.cleanupAbandonedRaidsFlags = flags;
  }

  connectFlags: __CallReducerFlags = 'FullUpdate';
  connect(flags: __CallReducerFlags) {
    this.connectFlags = flags;
  }

  createPrivateRoomFlags: __CallReducerFlags = 'FullUpdate';
  createPrivateRoom(flags: __CallReducerFlags) {
    this.createPrivateRoomFlags = flags;
  }

  joinPrivateRoomFlags: __CallReducerFlags = 'FullUpdate';
  joinPrivateRoom(flags: __CallReducerFlags) {
    this.joinPrivateRoomFlags = flags;
  }

  leaveCompletedRaidFlags: __CallReducerFlags = 'FullUpdate';
  leaveCompletedRaid(flags: __CallReducerFlags) {
    this.leaveCompletedRaidFlags = flags;
  }

  leaveRaidFlags: __CallReducerFlags = 'FullUpdate';
  leaveRaid(flags: __CallReducerFlags) {
    this.leaveRaidFlags = flags;
  }

  markEventSentFlags: __CallReducerFlags = 'FullUpdate';
  markEventSent(flags: __CallReducerFlags) {
    this.markEventSentFlags = flags;
  }

  openLootChestFlags: __CallReducerFlags = 'FullUpdate';
  openLootChest(flags: __CallReducerFlags) {
    this.openLootChestFlags = flags;
  }

  raidAgainFlags: __CallReducerFlags = 'FullUpdate';
  raidAgain(flags: __CallReducerFlags) {
    this.raidAgainFlags = flags;
  }

  requestProblemFlags: __CallReducerFlags = 'FullUpdate';
  requestProblem(flags: __CallReducerFlags) {
    this.requestProblemFlags = flags;
  }

  setGradeFlags: __CallReducerFlags = 'FullUpdate';
  setGrade(flags: __CallReducerFlags) {
    this.setGradeFlags = flags;
  }

  soloAgainFlags: __CallReducerFlags = 'FullUpdate';
  soloAgain(flags: __CallReducerFlags) {
    this.soloAgainFlags = flags;
  }

  startRaidManualFlags: __CallReducerFlags = 'FullUpdate';
  startRaidManual(flags: __CallReducerFlags) {
    this.startRaidManualFlags = flags;
  }

  startRematchFlags: __CallReducerFlags = 'FullUpdate';
  startRematch(flags: __CallReducerFlags) {
    this.startRematchFlags = flags;
  }

  startSoloRaidFlags: __CallReducerFlags = 'FullUpdate';
  startSoloRaid(flags: __CallReducerFlags) {
    this.startSoloRaidFlags = flags;
  }

  submitAnswerFlags: __CallReducerFlags = 'FullUpdate';
  submitAnswer(flags: __CallReducerFlags) {
    this.submitAnswerFlags = flags;
  }

  testCreateTimebackEventFlags: __CallReducerFlags = 'FullUpdate';
  testCreateTimebackEvent(flags: __CallReducerFlags) {
    this.testCreateTimebackEventFlags = flags;
  }

  toggleReadyFlags: __CallReducerFlags = 'FullUpdate';
  toggleReady(flags: __CallReducerFlags) {
    this.toggleReadyFlags = flags;
  }

}

export class RemoteTables {
  constructor(private connection: __DbConnectionImpl) {}

  get authorizedWorker(): AuthorizedWorkerTableHandle<'authorized_worker'> {
    // clientCache is a private property
    return new AuthorizedWorkerTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<AuthorizedWorker>(REMOTE_MODULE.tables.authorized_worker));
  }

  get cleanupSchedule(): CleanupScheduleTableHandle<'cleanup_schedule'> {
    // clientCache is a private property
    return new CleanupScheduleTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<CleanupSchedule>(REMOTE_MODULE.tables.cleanup_schedule));
  }

  get factMastery(): FactMasteryTableHandle<'fact_mastery'> {
    // clientCache is a private property
    return new FactMasteryTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<FactMastery>(REMOTE_MODULE.tables.fact_mastery));
  }

  get leaderboardEntry(): LeaderboardEntryTableHandle<'leaderboard_entry'> {
    // clientCache is a private property
    return new LeaderboardEntryTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<LeaderboardEntry>(REMOTE_MODULE.tables.leaderboard_entry));
  }

  get performanceSnapshot(): PerformanceSnapshotTableHandle<'performance_snapshot'> {
    // clientCache is a private property
    return new PerformanceSnapshotTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<PerformanceSnapshot>(REMOTE_MODULE.tables.performance_snapshot));
  }

  get player(): PlayerTableHandle<'player'> {
    // clientCache is a private property
    return new PlayerTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<Player>(REMOTE_MODULE.tables.player));
  }

  get playerAnswer(): PlayerAnswerTableHandle<'player_answer'> {
    // clientCache is a private property
    return new PlayerAnswerTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<PlayerAnswer>(REMOTE_MODULE.tables.player_answer));
  }

  get problem(): ProblemTableHandle<'problem'> {
    // clientCache is a private property
    return new ProblemTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<Problem>(REMOTE_MODULE.tables.problem));
  }

  get raid(): RaidTableHandle<'raid'> {
    // clientCache is a private property
    return new RaidTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<Raid>(REMOTE_MODULE.tables.raid));
  }

  get raidPlayer(): RaidPlayerTableHandle<'raid_player'> {
    // clientCache is a private property
    return new RaidPlayerTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<RaidPlayer>(REMOTE_MODULE.tables.raid_player));
  }

  get raidTimeoutSchedule(): RaidTimeoutScheduleTableHandle<'raid_timeout_schedule'> {
    // clientCache is a private property
    return new RaidTimeoutScheduleTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<RaidTimeoutSchedule>(REMOTE_MODULE.tables.raid_timeout_schedule));
  }

  get session(): SessionTableHandle<'session'> {
    // clientCache is a private property
    return new SessionTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<Session>(REMOTE_MODULE.tables.session));
  }

  get timebackEventQueue(): TimebackEventQueueTableHandle<'timeback_event_queue'> {
    // clientCache is a private property
    return new TimebackEventQueueTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<TimebackEventQueue>(REMOTE_MODULE.tables.timeback_event_queue));
  }
}

export class SubscriptionBuilder extends __SubscriptionBuilderImpl<RemoteTables, RemoteReducers, SetReducerFlags> { }

export class DbConnection extends __DbConnectionImpl<RemoteTables, RemoteReducers, SetReducerFlags> {
  static builder = (): __DbConnectionBuilder<DbConnection, ErrorContext, SubscriptionEventContext> => {
    return new __DbConnectionBuilder<DbConnection, ErrorContext, SubscriptionEventContext>(REMOTE_MODULE, (imp: __DbConnectionImpl) => imp as DbConnection);
  }
  subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  }
}

export type EventContext = __EventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags, Reducer>;
export type ReducerEventContext = __ReducerEventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags, Reducer>;
export type SubscriptionEventContext = __SubscriptionEventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags>;
export type ErrorContext = __ErrorContextInterface<RemoteTables, RemoteReducers, SetReducerFlags>;
