// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type TableHandle as __TableHandle,
} from "spacetimedb";

export type LeaderboardEntry = {
  id: bigint,
  grade: number,
  position: number,
  playerId: string,
  playerName: string,
  rank: string,
  division: string,
  masteryPercent: number,
  speedPercent: number,
};
let _cached_LeaderboardEntry_type_value: __AlgebraicTypeType | null = null;

/**
 * An object for generated helper functions.
 */
export const LeaderboardEntry = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    if (_cached_LeaderboardEntry_type_value) return _cached_LeaderboardEntry_type_value;
    _cached_LeaderboardEntry_type_value = __AlgebraicTypeValue.Product({ elements: [] });
    _cached_LeaderboardEntry_type_value.value.elements.push(
      { name: "id", algebraicType: __AlgebraicTypeValue.U64 },
      { name: "grade", algebraicType: __AlgebraicTypeValue.U8 },
      { name: "position", algebraicType: __AlgebraicTypeValue.U32 },
      { name: "playerId", algebraicType: __AlgebraicTypeValue.String },
      { name: "playerName", algebraicType: __AlgebraicTypeValue.String },
      { name: "rank", algebraicType: __AlgebraicTypeValue.String },
      { name: "division", algebraicType: __AlgebraicTypeValue.String },
      { name: "masteryPercent", algebraicType: __AlgebraicTypeValue.U32 },
      { name: "speedPercent", algebraicType: __AlgebraicTypeValue.U32 },
    );
    return _cached_LeaderboardEntry_type_value;
  },

  serialize(writer: __BinaryWriter, value: LeaderboardEntry): void {
    __AlgebraicTypeValue.serializeValue(writer, LeaderboardEntry.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): LeaderboardEntry {
    return __AlgebraicTypeValue.deserializeValue(reader, LeaderboardEntry.getTypeScriptAlgebraicType());
  },

}

export default LeaderboardEntry;


