// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type TableHandle as __TableHandle,
} from "spacetimedb";
import * as OperationVariants from './operation_variants'

// The tagged union or sum type for the algebraic type `Operation`.
export type Operation = OperationVariants.Add |
  OperationVariants.Subtract |
  OperationVariants.Multiply |
  OperationVariants.Divide;

let _cached_Operation_type_value: __AlgebraicTypeType | null = null;

// A value with helper functions to construct the type.
export const Operation = {
  // Helper functions for constructing each variant of the tagged union.
  // ```
  // const foo = Foo.A(42);
  // assert!(foo.tag === "A");
  // assert!(foo.value === 42);
  // ```
  Add: { tag: "Add" } as const,
  Subtract: { tag: "Subtract" } as const,
  Multiply: { tag: "Multiply" } as const,
  Divide: { tag: "Divide" } as const,

  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    if (_cached_Operation_type_value) return _cached_Operation_type_value;
    _cached_Operation_type_value = __AlgebraicTypeValue.Sum({ variants: [] });
    _cached_Operation_type_value.value.variants.push(
      { name: "Add", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      { name: "Subtract", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      { name: "Multiply", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      { name: "Divide", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
    );
    return _cached_Operation_type_value;
  },

  serialize(writer: __BinaryWriter, value: Operation): void {
      __AlgebraicTypeValue.serializeValue(writer, Operation.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): Operation {
      return __AlgebraicTypeValue.deserializeValue(reader, Operation.getTypeScriptAlgebraicType());
  },

}

export default Operation;


