// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type TableHandle as __TableHandle,
} from "spacetimedb";
import { Operation } from "./operation_type";
// Mark import as potentially unused
declare type __keep_Operation = Operation;


export type Problem = {
  id: bigint,
  raidId: bigint,
  playerId: string,
  leftOperand: number,
  rightOperand: number,
  operation: Operation,
  answer: number,
  issuedAt: __Timestamp,
  sequence: number,
};
let _cached_Problem_type_value: __AlgebraicTypeType | null = null;

/**
 * An object for generated helper functions.
 */
export const Problem = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    if (_cached_Problem_type_value) return _cached_Problem_type_value;
    _cached_Problem_type_value = __AlgebraicTypeValue.Product({ elements: [] });
    _cached_Problem_type_value.value.elements.push(
      { name: "id", algebraicType: __AlgebraicTypeValue.U64 },
      { name: "raidId", algebraicType: __AlgebraicTypeValue.U64 },
      { name: "playerId", algebraicType: __AlgebraicTypeValue.String },
      { name: "leftOperand", algebraicType: __AlgebraicTypeValue.U8 },
      { name: "rightOperand", algebraicType: __AlgebraicTypeValue.U8 },
      { name: "operation", algebraicType: Operation.getTypeScriptAlgebraicType() },
      { name: "answer", algebraicType: __AlgebraicTypeValue.U16 },
      { name: "issuedAt", algebraicType: __AlgebraicTypeValue.createTimestampType() },
      { name: "sequence", algebraicType: __AlgebraicTypeValue.U32 },
    );
    return _cached_Problem_type_value;
  },

  serialize(writer: __BinaryWriter, value: Problem): void {
    __AlgebraicTypeValue.serializeValue(writer, Problem.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): Problem {
    return __AlgebraicTypeValue.deserializeValue(reader, Problem.getTypeScriptAlgebraicType());
  },

}

export default Problem;


