// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type TableHandle as __TableHandle,
} from "spacetimedb";
import * as RaidStateVariants from './raid_state_variants'

// The tagged union or sum type for the algebraic type `RaidState`.
export type RaidState = RaidStateVariants.Matchmaking |
  RaidStateVariants.InProgress |
  RaidStateVariants.Victory |
  RaidStateVariants.Failed |
  RaidStateVariants.Rematch;

let _cached_RaidState_type_value: __AlgebraicTypeType | null = null;

// A value with helper functions to construct the type.
export const RaidState = {
  // Helper functions for constructing each variant of the tagged union.
  // ```
  // const foo = Foo.A(42);
  // assert!(foo.tag === "A");
  // assert!(foo.value === 42);
  // ```
  Matchmaking: { tag: "Matchmaking" } as const,
  InProgress: { tag: "InProgress" } as const,
  Victory: { tag: "Victory" } as const,
  Failed: { tag: "Failed" } as const,
  Rematch: { tag: "Rematch" } as const,

  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    if (_cached_RaidState_type_value) return _cached_RaidState_type_value;
    _cached_RaidState_type_value = __AlgebraicTypeValue.Sum({ variants: [] });
    _cached_RaidState_type_value.value.variants.push(
      { name: "Matchmaking", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      { name: "InProgress", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      { name: "Victory", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      { name: "Failed", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      { name: "Rematch", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
    );
    return _cached_RaidState_type_value;
  },

  serialize(writer: __BinaryWriter, value: RaidState): void {
      __AlgebraicTypeValue.serializeValue(writer, RaidState.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): RaidState {
      return __AlgebraicTypeValue.deserializeValue(reader, RaidState.getTypeScriptAlgebraicType());
  },

}

export default RaidState;


