// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type TableHandle as __TableHandle,
} from "spacetimedb";

export type RaidPlayer = {
  id: bigint,
  playerId: string,
  raidId: bigint,
  playerName: string,
  grade: number,
  rank: string | undefined,
  division: string | undefined,
  isActive: boolean,
  damageDealt: number,
  problemsAnswered: number,
  correctAnswers: number,
  fastestAnswerMs: number,
  isReady: boolean,
  isLeader: boolean,
  recentProblems: string,
  pendingChestBonus: number | undefined,
  track: string | undefined,
};
let _cached_RaidPlayer_type_value: __AlgebraicTypeType | null = null;

/**
 * An object for generated helper functions.
 */
export const RaidPlayer = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    if (_cached_RaidPlayer_type_value) return _cached_RaidPlayer_type_value;
    _cached_RaidPlayer_type_value = __AlgebraicTypeValue.Product({ elements: [] });
    _cached_RaidPlayer_type_value.value.elements.push(
      { name: "id", algebraicType: __AlgebraicTypeValue.U64 },
      { name: "playerId", algebraicType: __AlgebraicTypeValue.String },
      { name: "raidId", algebraicType: __AlgebraicTypeValue.U64 },
      { name: "playerName", algebraicType: __AlgebraicTypeValue.String },
      { name: "grade", algebraicType: __AlgebraicTypeValue.U8 },
      { name: "rank", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.String) },
      { name: "division", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.String) },
      { name: "isActive", algebraicType: __AlgebraicTypeValue.Bool },
      { name: "damageDealt", algebraicType: __AlgebraicTypeValue.U32 },
      { name: "problemsAnswered", algebraicType: __AlgebraicTypeValue.U32 },
      { name: "correctAnswers", algebraicType: __AlgebraicTypeValue.U32 },
      { name: "fastestAnswerMs", algebraicType: __AlgebraicTypeValue.U32 },
      { name: "isReady", algebraicType: __AlgebraicTypeValue.Bool },
      { name: "isLeader", algebraicType: __AlgebraicTypeValue.Bool },
      { name: "recentProblems", algebraicType: __AlgebraicTypeValue.String },
      { name: "pendingChestBonus", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.U32) },
      { name: "track", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.String) },
    );
    return _cached_RaidPlayer_type_value;
  },

  serialize(writer: __BinaryWriter, value: RaidPlayer): void {
    __AlgebraicTypeValue.serializeValue(writer, RaidPlayer.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): RaidPlayer {
    return __AlgebraicTypeValue.deserializeValue(reader, RaidPlayer.getTypeScriptAlgebraicType());
  },

}

export default RaidPlayer;


