// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type TableHandle as __TableHandle,
} from "spacetimedb";
import { RaidState } from "./raid_state_type";
// Mark import as potentially unused
declare type __keep_RaidState = RaidState;


export type Raid = {
  id: bigint,
  bossHp: number,
  bossMaxHp: number,
  state: RaidState,
  roomCode: string | undefined,
  startedAt: __Timestamp,
  durationSeconds: number | undefined,
  problemsIssued: number,
  maxProblems: number,
};
let _cached_Raid_type_value: __AlgebraicTypeType | null = null;

/**
 * An object for generated helper functions.
 */
export const Raid = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    if (_cached_Raid_type_value) return _cached_Raid_type_value;
    _cached_Raid_type_value = __AlgebraicTypeValue.Product({ elements: [] });
    _cached_Raid_type_value.value.elements.push(
      { name: "id", algebraicType: __AlgebraicTypeValue.U64 },
      { name: "bossHp", algebraicType: __AlgebraicTypeValue.U32 },
      { name: "bossMaxHp", algebraicType: __AlgebraicTypeValue.U32 },
      { name: "state", algebraicType: RaidState.getTypeScriptAlgebraicType() },
      { name: "roomCode", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.String) },
      { name: "startedAt", algebraicType: __AlgebraicTypeValue.createTimestampType() },
      { name: "durationSeconds", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.U32) },
      { name: "problemsIssued", algebraicType: __AlgebraicTypeValue.U32 },
      { name: "maxProblems", algebraicType: __AlgebraicTypeValue.U32 },
    );
    return _cached_Raid_type_value;
  },

  serialize(writer: __BinaryWriter, value: Raid): void {
    __AlgebraicTypeValue.serializeValue(writer, Raid.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): Raid {
    return __AlgebraicTypeValue.deserializeValue(reader, Raid.getTypeScriptAlgebraicType());
  },

}

export default Raid;


