// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type TableHandle as __TableHandle,
} from "spacetimedb";

export type TestCreateTimebackEvent = {
  playerId: string,
  timebackId: string,
  raidId: bigint,
  email: string,
  xpEarned: number,
  level: number,
  problemsAnswered: number,
  correctAnswers: number,
};
let _cached_TestCreateTimebackEvent_type_value: __AlgebraicTypeType | null = null;

/**
 * An object for generated helper functions.
 */
export const TestCreateTimebackEvent = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    if (_cached_TestCreateTimebackEvent_type_value) return _cached_TestCreateTimebackEvent_type_value;
    _cached_TestCreateTimebackEvent_type_value = __AlgebraicTypeValue.Product({ elements: [] });
    _cached_TestCreateTimebackEvent_type_value.value.elements.push(
      { name: "playerId", algebraicType: __AlgebraicTypeValue.String },
      { name: "timebackId", algebraicType: __AlgebraicTypeValue.String },
      { name: "raidId", algebraicType: __AlgebraicTypeValue.U64 },
      { name: "email", algebraicType: __AlgebraicTypeValue.String },
      { name: "xpEarned", algebraicType: __AlgebraicTypeValue.F32 },
      { name: "level", algebraicType: __AlgebraicTypeValue.U8 },
      { name: "problemsAnswered", algebraicType: __AlgebraicTypeValue.U32 },
      { name: "correctAnswers", algebraicType: __AlgebraicTypeValue.U32 },
    );
    return _cached_TestCreateTimebackEvent_type_value;
  },

  serialize(writer: __BinaryWriter, value: TestCreateTimebackEvent): void {
    __AlgebraicTypeValue.serializeValue(writer, TestCreateTimebackEvent.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): TestCreateTimebackEvent {
    return __AlgebraicTypeValue.deserializeValue(reader, TestCreateTimebackEvent.getTypeScriptAlgebraicType());
  },

}

export default TestCreateTimebackEvent;

