// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type TableHandle as __TableHandle,
} from "spacetimedb";

export type TimebackEventQueue = {
  id: bigint,
  playerId: string,
  payload: string,
  createdAt: __Timestamp,
  sent: boolean,
  attempts: number,
  nextRetryAt: __Timestamp | undefined,
  lastError: string | undefined,
  sentAt: __Timestamp | undefined,
};
let _cached_TimebackEventQueue_type_value: __AlgebraicTypeType | null = null;

/**
 * An object for generated helper functions.
 */
export const TimebackEventQueue = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    if (_cached_TimebackEventQueue_type_value) return _cached_TimebackEventQueue_type_value;
    _cached_TimebackEventQueue_type_value = __AlgebraicTypeValue.Product({ elements: [] });
    _cached_TimebackEventQueue_type_value.value.elements.push(
      { name: "id", algebraicType: __AlgebraicTypeValue.U64 },
      { name: "playerId", algebraicType: __AlgebraicTypeValue.String },
      { name: "payload", algebraicType: __AlgebraicTypeValue.String },
      { name: "createdAt", algebraicType: __AlgebraicTypeValue.createTimestampType() },
      { name: "sent", algebraicType: __AlgebraicTypeValue.Bool },
      { name: "attempts", algebraicType: __AlgebraicTypeValue.U8 },
      { name: "nextRetryAt", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.createTimestampType()) },
      { name: "lastError", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.String) },
      { name: "sentAt", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.createTimestampType()) },
    );
    return _cached_TimebackEventQueue_type_value;
  },

  serialize(writer: __BinaryWriter, value: TimebackEventQueue): void {
    __AlgebraicTypeValue.serializeValue(writer, TimebackEventQueue.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): TimebackEventQueue {
    return __AlgebraicTypeValue.deserializeValue(reader, TimebackEventQueue.getTypeScriptAlgebraicType());
  },

}

export default TimebackEventQueue;


