// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import AttemptRecord from "./attempt_record_type";


export default __t.object("FactMastery", {
  id: __t.u64(),
  playerId: __t.string(),
  factKey: __t.string(),
  totalAttempts: __t.u32(),
  totalCorrect: __t.u32(),
  lastSeen: __t.timestamp(),
  avgResponseMs: __t.u32(),
  fastestMs: __t.u32(),
  get recentAttempts() {
    return __t.array(AttemptRecord);
  },
  masteryLevel: __t.u8(),
});


