// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import Operation from "./operation_type";


export default __t.row({
  id: __t.u64().primaryKey(),
  raidId: __t.u64(),
  playerId: __t.string(),
  leftOperand: __t.u8(),
  rightOperand: __t.u8(),
  get operation() {
    return Operation;
  },
  answer: __t.u16(),
  issuedAt: __t.timestamp(),
  sequence: __t.u32(),
});
