// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import RaidState from "./raid_state_type";


export default __t.row({
  id: __t.u64().primaryKey(),
  bossHp: __t.u32(),
  bossMaxHp: __t.u32(),
  get state() {
    return RaidState;
  },
  roomCode: __t.option(__t.string()),
  startedAt: __t.timestamp(),
  pauseStartedAt: __t.option(__t.timestamp()),
  durationSeconds: __t.option(__t.u32()),
  problemsIssued: __t.u32(),
  maxProblems: __t.u32(),
  bossLevel: __t.u8(),
  countdownStartedAt: __t.option(__t.timestamp()),
});
