// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  playerId: __t.string(),
  timebackId: __t.string(),
  raidId: __t.u64(),
  email: __t.string(),
  xpEarned: __t.f32(),
  level: __t.u8(),
  problemsAnswered: __t.u32(),
  correctAnswers: __t.u32(),
};
